#! /bin/sh

# - autostart
picom -b &
killall sxhkd; sxhkd &
killall dunst; dunst &
xrandr --output HDMI-1 --brightness 0.4 &
feh --bg-fill $HOME/Pictures/14.jpg &
xsetroot -cursor_name left_ptr &
$HOME/.config/polybar/launch.sh &
setxkbmap br

# - variables
alias bc='bspc config'
alias br='bspc rule'

#Workspaces
bspc monitor HDMI-1 -d 1 2 3 4 5 6

#Others
bc border_width 0
bc window_gap 10
bc split_ratio 0.52
bc borderless_monocle true
bc gapless_monocle false

#rules
br -a Zathura state=tiled
