#! /bin/sh

# autostart
killall sxhkd; pgrep -x sxhkd > /dev/null || sxhkd &
killall picom; picom &
killall dunst; dunst &
xrandr --output HDMI-1 --brightness 0.4 &
feh --bg-fill $HOME/Pictures/07.jpg &
xsetroot -cursor_name left_ptr &
$HOME/.config/polybar/launch.sh &
OUT=$(echo "$@" | sed "s:///:////:g" | sed "s/%20/ /g") &
kitty -T "Ranger File Manager" -x ranger "$OUT" &
setxkbmap br

# variables
alias bc='bspc config'
alias br='bspc rule'

# workspaces
bspc monitor -d 1 2 3 4 5 6

# others
bc border_width 0
bc window_gap 10
bc split_ratio 0.54
bc borderless_monocle true
bc gapless_monocle false
